
spring:
  application:
    name: ddp_study_management

  config:
    import: classpath:env.properties

  datasource:
    url: ${DATASOURCE_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true
    show-sql: true

#  sql:
#    init:
#      mode: never
###      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql
#